add single key multi lock test

diff --git a/run-tests b/run-tests
--- a/run-tests
+++ b/run-tests
@@ -55,12 +55,14 @@ please run 'slock' on your changes before committing."
     exit 1
 fi
 
+echo
+
 BENCH_CMD="go run benchmarks/benchmark/benchmark.go --client=16 --conc=64 --count=500000"
 BENCH_OUTPUTS=$(which timeout > /dev/null 2>&1 && timeout 120 $BENCH_CMD 2>&1 || $BENCH_CMD 2>&1)
 BENCH_SUCCEDS=$(echo "$BENCH_OUTPUTS" | grep "Succed")
 if [ -z "$SLOCK_PS" ]
     then
-        log_error "slock benchmark failed for the following reasons:
+        log_error "slock benchmark multi key single lock failed for the following reasons:
                    $BENCH_OUTPUTS
 please run 'go run benchmarks/benchmark/benchmark.go' on your changes before committing."
 
@@ -69,7 +71,25 @@ please run 'go run benchmarks/benchmark/benchmark.go' on your changes before com
     exit 1
 fi
 
-echo "Benchmark Info:
+echo "Benchmark Multi Key Single Lock Info:
+$BENCH_OUTPUTS
+"
+
+BENCH_CMD="go run benchmarks/benchmark/benchmark.go --client=16 --conc=64 --count=200000"
+BENCH_OUTPUTS=$(which timeout > /dev/null 2>&1 && timeout 120 $BENCH_CMD 2>&1 || $BENCH_CMD 2>&1)
+BENCH_SUCCEDS=$(echo "$BENCH_OUTPUTS" | grep "Succed")
+if [ -z "$SLOCK_PS" ]
+    then
+        log_error "slock benchmark single key multi lock failed for the following reasons:
+                   $BENCH_OUTPUTS
+please run 'go run benchmarks/benchmark3/benchmark.go' on your changes before committing."
+
+    ps -ef | grep slock | grep -v grep | awk '{print $2}' | xargs kill -HUP > /dev/null 2>&1
+    ps -ef | grep benchmark | grep -v grep | awk '{print $2}' | xargs kill -HUP > /dev/null 2>&1
+    exit 1
+fi
+
+echo "Benchmark Single Key Multi Lock Info:
 $BENCH_OUTPUTS
 "
 
