update CI run-tests

diff --git a/run-tests b/run-tests
--- a/run-tests
+++ b/run-tests
@@ -39,21 +39,56 @@ run_gotest "github.com/snower/slock/protocol"
 run_gotest "github.com/snower/slock/server"
 
 export PATH=$(pwd):$PATH
+WORKLOAD_DIR="/tmp/$(date '+%Y%m%d%H%M%S')/"
+mkdir $WORKLOAD_DIR
 
-DATA_DIR="/tmp/$(date '+%Y%m%d%H%M%S')/"
+DATA_DIR="${WORKLOAD_DIR}/data5657/"
 mkdir $DATA_DIR
+cp .github/data/5657-meta.pb $DATA_DIR
 LOG_FILENAME="${DATA_DIR}slock.log"
-slock --data_dir="$DATA_DIR" > $LOG_FILENAME 2>&1 &
-
-SLOCK_PS=$(ps aux | grep slock | grep -v grep)
+slock --port=5657 --data_dir="$DATA_DIR" > $LOG_FILENAME 2>&1 &
+SLOCK_PS=$(ps aux | grep slock | grep 5657 | grep -v grep)
 if [ -z "$SLOCK_PS" ]
     then
         SLOCK_ERRORS=$(slock 2>&1)
-        log_error "slock start failed for the following reasons:
+        log_error "slock start 5657 failed for the following reasons:
                    $SLOCK_ERRORS
 please run 'slock' on your changes before committing."
     exit 1
 fi
+sleep 3
+
+DATA_DIR="${WORKLOAD_DIR}/data5659/"
+mkdir $DATA_DIR
+cp .github/data/5659-meta.pb $DATA_DIR
+LOG_FILENAME="${DATA_DIR}slock.log"
+slock --port=5659 --data_dir="$DATA_DIR" > $LOG_FILENAME 2>&1 &
+SLOCK_PS=$(ps aux | grep slock | grep 5659 | grep -v grep)
+if [ -z "$SLOCK_PS" ]
+    then
+        SLOCK_ERRORS=$(slock 2>&1)
+        log_error "slock start 5659 failed for the following reasons:
+                   $SLOCK_ERRORS
+please run 'slock' on your changes before committing."
+    exit 1
+fi
+sleep 3
+
+DATA_DIR="${WORKLOAD_DIR}/data5658/"
+mkdir $DATA_DIR
+cp .github/data/5658-meta.pb $DATA_DIR
+LOG_FILENAME="${DATA_DIR}slock.log"
+slock --port=5658 --data_dir="$DATA_DIR" > $LOG_FILENAME 2>&1 &
+SLOCK_PS=$(ps aux | grep slock | grep 5658 | grep -v grep)
+if [ -z "$SLOCK_PS" ]
+    then
+        SLOCK_ERRORS=$(slock 2>&1)
+        log_error "slock start 5658 failed for the following reasons:
+                   $SLOCK_ERRORS
+please run 'slock' on your changes before committing."
+    exit 1
+fi
+sleep 3
 
 run_gotest "github.com/snower/slock/client"
 
@@ -155,7 +190,7 @@ Benchmark Multi Key Single Require Ack And Lock With Data Info:
 $BENCH_OUTPUTS
 "
 
-BENCH_CMD="go run tools/benchmark/main.go --mode=stream --client=4 --conc=16 --count=1000000"
+BENCH_CMD="go run tools/benchmark/main.go --port=5659 --mode=stream --client=4 --conc=16 --count=1000000"
 BENCH_OUTPUTS=$(which timeout > /dev/null 2>&1 && timeout 120 $BENCH_CMD 2>&1 || $BENCH_CMD 2>&1)
 BENCH_SUCCEDS=$(echo "$BENCH_OUTPUTS" | grep "Succed")
 if [ -z "$BENCH_SUCCEDS" ]
@@ -175,8 +210,16 @@ $BENCH_OUTPUTS
 "
 
 sleep 3
-SLOCK_INFOS=$(slock info 2>&1)
-echo "Slock Info:
+SLOCK_INFOS=$(slock info --port=5658 2>&1)
+echo "Slock 5658 Info:
+$SLOCK_INFOS
+"
+SLOCK_INFOS=$(slock info --port=5657 2>&1)
+echo "Slock 5657 Info:
+$SLOCK_INFOS
+"
+SLOCK_INFOS=$(slock info --port=5659 2>&1)
+echo "Slock 5659 Info:
 $SLOCK_INFOS
 "
 
@@ -189,7 +232,7 @@ ps -ef | grep benchmark | grep -v grep | awk '{print $2}' | xargs kill -HUP > /d
 sleep 2
 
 echo "Slock Log:"
-cat $LOG_FILENAME | grep -v Protocol | grep -v Connection
+cat $LOG_FILENAME | grep -v protocol | grep -v connection
 echo
 
 exit 0
