update run-tests

diff --git a/run-tests b/run-tests
--- a/run-tests
+++ b/run-tests
@@ -60,7 +60,7 @@ run_gotest "github.com/snower/slock/client"
 echo "Run Benchmark"
 echo
 
-BENCH_CMD="go run tools/benchmark/main.go --client=4 --conc=16 --count=50000"
+BENCH_CMD="go run tools/benchmark/main.go --client=4 --conc=16 --count=200000"
 BENCH_OUTPUTS=$(which timeout > /dev/null 2>&1 && timeout 120 $BENCH_CMD 2>&1 || $BENCH_CMD 2>&1)
 BENCH_SUCCEDS=$(echo "$BENCH_OUTPUTS" | grep "Succed")
 if [ -z "$BENCH_SUCCEDS" ]
@@ -78,14 +78,14 @@ echo "Benchmark Multi Key Single Lock Info:
 $BENCH_OUTPUTS
 "
 
-BENCH_CMD="go run tools/benchmark/main.go --key=1 --client=4 --conc=16 --count=50000"
+BENCH_CMD="go run tools/benchmark/main.go --key=1 --client=4 --conc=16 --count=80000"
 BENCH_OUTPUTS=$(which timeout > /dev/null 2>&1 && timeout 120 $BENCH_CMD 2>&1 || $BENCH_CMD 2>&1)
 BENCH_SUCCEDS=$(echo "$BENCH_OUTPUTS" | grep "Succed")
 if [ -z "$BENCH_SUCCEDS" ]
     then
         log_error "slock benchmark single key multi lock failed for the following reasons:
                    $BENCH_OUTPUTS
-please run 'go run benchmarks/benchmark3/benchmark.go' on your changes before committing."
+please run 'go run benchmarks/benchmark/benchmark.go' on your changes before committing."
 
     ps -ef | grep slock | grep -v grep | awk '{print $2}' | xargs kill -HUP > /dev/null 2>&1
     ps -ef | grep benchmark | grep -v grep | awk '{print $2}' | xargs kill -HUP > /dev/null 2>&1
@@ -96,14 +96,68 @@ echo "Benchmark Single Key Multi Lock Info:
 $BENCH_OUTPUTS
 "
 
-BENCH_CMD="go run tools/benchmark/main.go --mode=stream --client=4 --conc=16 --count=200000"
+BENCH_CMD="go run tools/benchmark/main.go --client=4 --conc=16 --count=20000 --timeout_flag=4096"
+BENCH_OUTPUTS=$(which timeout > /dev/null 2>&1 && timeout 120 $BENCH_CMD 2>&1 || $BENCH_CMD 2>&1)
+BENCH_SUCCEDS=$(echo "$BENCH_OUTPUTS" | grep "Succed")
+if [ -z "$BENCH_SUCCEDS" ]
+    then
+        log_error "slock benchmark multi key multi lock require ack failed for the following reasons:
+                   $BENCH_OUTPUTS
+please run 'go run benchmarks/benchmark/benchmark.go' on your changes before committing."
+
+    ps -ef | grep slock | grep -v grep | awk '{print $2}' | xargs kill -HUP > /dev/null 2>&1
+    ps -ef | grep benchmark | grep -v grep | awk '{print $2}' | xargs kill -HUP > /dev/null 2>&1
+    exit 1
+fi
+
+echo "Benchmark Multi Key Multi Lock Require Ack Info:
+$BENCH_OUTPUTS
+"
+
+BENCH_CMD="go run tools/benchmark/main.go --client=4 --conc=16 --count=40000 --data_length=4096"
+BENCH_OUTPUTS=$(which timeout > /dev/null 2>&1 && timeout 120 $BENCH_CMD 2>&1 || $BENCH_CMD 2>&1)
+BENCH_SUCCEDS=$(echo "$BENCH_OUTPUTS" | grep "Succed")
+if [ -z "$BENCH_SUCCEDS" ]
+    then
+        log_error "slock benchmark multi key multi lock with data failed for the following reasons:
+                   $BENCH_OUTPUTS
+please run 'go run benchmarks/benchmark/benchmark.go' on your changes before committing."
+
+    ps -ef | grep slock | grep -v grep | awk '{print $2}' | xargs kill -HUP > /dev/null 2>&1
+    ps -ef | grep benchmark | grep -v grep | awk '{print $2}' | xargs kill -HUP > /dev/null 2>&1
+    exit 1
+fi
+
+echo "Benchmark Multi Key Multi Lock With Data Info:
+$BENCH_OUTPUTS
+"
+
+BENCH_CMD="go run tools/benchmark/main.go --client=4 --conc=16 --count=10000  --timeout_flag=4096 --data_length=4096"
+BENCH_OUTPUTS=$(which timeout > /dev/null 2>&1 && timeout 120 $BENCH_CMD 2>&1 || $BENCH_CMD 2>&1)
+BENCH_SUCCEDS=$(echo "$BENCH_OUTPUTS" | grep "Succed")
+if [ -z "$BENCH_SUCCEDS" ]
+    then
+        log_error "slock benchmark multi key multi lock require ack and with data failed for the following reasons:
+                   $BENCH_OUTPUTS
+please run 'go run benchmarks/benchmark/benchmark.go' on your changes before committing."
+
+    ps -ef | grep slock | grep -v grep | awk '{print $2}' | xargs kill -HUP > /dev/null 2>&1
+    ps -ef | grep benchmark | grep -v grep | awk '{print $2}' | xargs kill -HUP > /dev/null 2>&1
+    exit 1
+fi
+
+echo "Benchmark Multi Key Multi Require Ack And Lock With Data Info:
+$BENCH_OUTPUTS
+"
+
+BENCH_CMD="go run tools/benchmark/main.go --mode=stream --client=4 --conc=16 --count=500000"
 BENCH_OUTPUTS=$(which timeout > /dev/null 2>&1 && timeout 120 $BENCH_CMD 2>&1 || $BENCH_CMD 2>&1)
 BENCH_SUCCEDS=$(echo "$BENCH_OUTPUTS" | grep "Succed")
 if [ -z "$BENCH_SUCCEDS" ]
     then
         log_error "slock benchmark parallel lock failed for the following reasons:
                    $BENCH_OUTPUTS
-please run 'go run benchmarks/benchmark2/benchmark.go' on your changes before committing."
+please run 'go run benchmarks/benchmark/benchmark.go' on your changes before committing."
 
     ps -ef | grep slock | grep -v grep | awk '{print $2}' | xargs kill -HUP > /dev/null 2>&1
     ps -ef | grep benchmark | grep -v grep | awk '{print $2}' | xargs kill -HUP > /dev/null 2>&1
