run-tests add slock info test

diff --git a/run-tests b/run-tests
--- a/run-tests
+++ b/run-tests
@@ -54,7 +54,7 @@ fi
 
 BENCH_CMD="go run benchmarks/benchmark/benchmark.go --client=16 --conc=64 --count=500000"
 BENCH_OUTPUTS=$(which timeout > /dev/null 2>&1 && timeout 120 $BENCH_CMD 2>&1 || $BENCH_CMD 2>&1)
-BENCH_SUCCEDS=$(echo $BENCH_OUTPUTS | grep "Succed")
+BENCH_SUCCEDS=$(echo "$BENCH_OUTPUTS" | grep "Succed")
 if [ -z "$SLOCK_PS" ]
     then
         log_error "slock benchmark failed for the following reasons:
@@ -68,6 +68,28 @@ fi
 
 echo "Benchmark Info:
 $BENCH_OUTPUTS
+"
+
+sleep 3
+
+SLOCK_INFOS=$(slock info 2>&1)
+for INFO_KEY in "LockedCount" "WaitCount" "KeyCount"
+do
+    INFO_COUNT=$(echo "$SLOCK_INFOS" | grep $INFO_KEY | awk '{print $2}')
+    if [ "$INFO_COUNT" != "0" ]
+    then
+        log_error "slock info Error for the following reasons:
+$SLOCK_INFOS
+please run 'slock info' on your changes before committing."
+
+        ps -ef | grep slock | grep -v grep | awk '{print $2}' | xargs kill -9 > /dev/null 2>&1
+        ps -ef | grep benchmark | grep -v grep | awk '{print $2}' | xargs kill -9 > /dev/null 2>&1
+        exit 1
+    fi
+done
+
+echo "Slock Info:
+$SLOCK_INFOS
 "
 
 ps -ef | grep slock | grep -v grep | awk '{print $2}' | xargs kill -9 > /dev/null 2>&1
