update travis-ci test

diff --git a/run-tests b/run-tests
--- a/run-tests
+++ b/run-tests
@@ -75,7 +75,7 @@ echo "Benchmark Multi Key Single Lock Info:
 $BENCH_OUTPUTS
 "
 
-BENCH_CMD="go run benchmarks/benchmark/benchmark.go --client=16 --conc=64 --count=200000"
+BENCH_CMD="go run benchmarks/benchmark3/benchmark.go --client=16 --conc=64 --count=200000"
 BENCH_OUTPUTS=$(which timeout > /dev/null 2>&1 && timeout 120 $BENCH_CMD 2>&1 || $BENCH_CMD 2>&1)
 BENCH_SUCCEDS=$(echo "$BENCH_OUTPUTS" | grep "Succed")
 if [ -z "$SLOCK_PS" ]
@@ -90,6 +90,24 @@ please run 'go run benchmarks/benchmark3/benchmark.go' on your changes before co
 fi
 
 echo "Benchmark Single Key Multi Lock Info:
+$BENCH_OUTPUTS
+"
+
+BENCH_CMD="go run benchmarks/benchmark2/benchmark.go --client=16 --conc=64 --count=200000"
+BENCH_OUTPUTS=$(which timeout > /dev/null 2>&1 && timeout 120 $BENCH_CMD 2>&1 || $BENCH_CMD 2>&1)
+BENCH_SUCCEDS=$(echo "$BENCH_OUTPUTS" | grep "Succed")
+if [ -z "$SLOCK_PS" ]
+    then
+        log_error "slock benchmark parallel lock failed for the following reasons:
+                   $BENCH_OUTPUTS
+please run 'go run benchmarks/benchmark2/benchmark.go' on your changes before committing."
+
+    ps -ef | grep slock | grep -v grep | awk '{print $2}' | xargs kill -HUP > /dev/null 2>&1
+    ps -ef | grep benchmark | grep -v grep | awk '{print $2}' | xargs kill -HUP > /dev/null 2>&1
+    exit 1
+fi
+
+echo "Benchmark Parallel Lock Info:
 $BENCH_OUTPUTS
 "
 
