Add TreeLock and Exector to perform benchmark stress testing

diff --git a/run-tests b/run-tests
--- a/run-tests
+++ b/run-tests
@@ -213,6 +213,44 @@ Benchmark Transparency Multi Key Single Lock Info:
 $BENCH_OUTPUTS
 "
 
+BENCH_CMD="go run tools/benchmark/main.go --port=5659 --mode=tree --client=4 --conc=16 --count=200000"
+BENCH_OUTPUTS=$(which timeout > /dev/null 2>&1 && timeout 120 $BENCH_CMD 2>&1 || $BENCH_CMD 2>&1)
+BENCH_SUCCEDS=$(echo "$BENCH_OUTPUTS" | grep "Succed")
+if [ -z "$BENCH_SUCCEDS" ]
+    then
+        log_error "slock benchmark tree lock failed for the following reasons:
+                   $BENCH_OUTPUTS
+please run 'go run benchmarks/benchmark/benchmark.go' on your changes before committing."
+
+    ps -ef | grep slock | grep -v grep | awk '{print $2}' | xargs kill -HUP > /dev/null 2>&1
+    ps -ef | grep benchmark | grep -v grep | awk '{print $2}' | xargs kill -HUP > /dev/null 2>&1
+    exit 1
+fi
+
+echo "
+Benchmark Tree Lock Info:
+$BENCH_OUTPUTS
+"
+
+BENCH_CMD="go run tools/benchmark/main.go --port=5659 --client=4 --conc=64 --count=200000 --data_length=4096 --data_rate=0 --data_type=1"
+BENCH_OUTPUTS=$(which timeout > /dev/null 2>&1 && timeout 120 $BENCH_CMD 2>&1 || $BENCH_CMD 2>&1)
+BENCH_SUCCEDS=$(echo "$BENCH_OUTPUTS" | grep "Succed")
+if [ -z "$BENCH_SUCCEDS" ]
+    then
+        log_error "slock benchmark executor lock failed for the following reasons:
+                   $BENCH_OUTPUTS
+please run 'go run benchmarks/benchmark/benchmark.go' on your changes before committing."
+
+    ps -ef | grep slock | grep -v grep | awk '{print $2}' | xargs kill -HUP > /dev/null 2>&1
+    ps -ef | grep benchmark | grep -v grep | awk '{print $2}' | xargs kill -HUP > /dev/null 2>&1
+    exit 1
+fi
+
+echo "
+Benchmark Executor Lock Info:
+$BENCH_OUTPUTS
+"
+
 BENCH_CMD="go run tools/benchmark/main.go --port=5659 --mode=stream --client=4 --conc=16 --count=5000000"
 BENCH_OUTPUTS=$(which timeout > /dev/null 2>&1 && timeout 120 $BENCH_CMD 2>&1 || $BENCH_CMD 2>&1)
 BENCH_SUCCEDS=$(echo "$BENCH_OUTPUTS" | grep "Succed")
